sudo: required
language: python
python: "3.7"

addons:
  postgresql: "12"
  apt:
    packages:
    - postgresql-12
    - postgresql-client-12

before_install:
  - nvm install 14

env:
  global:
    # See https://docs.travis-ci.com/user/database-setup/#using-a-different-postgresql-version
    - PGPORT=5433
    - PGVER=12

install:
  - npm install
  - pip3 install tox

script:
  - psql -c 'create database squiggy_test'
  - psql squiggy_test -c 'create extension pg_trgm'
  - psql squiggy_test -c "create role squiggy superuser login password 'squiggy'; alter schema public owner to squiggy"
  - pip3 install -r requirements.txt
  - tox --parallel || travis_terminate 1
